environment: production
chdir: /home/ns_stats/www/ns_stats/current/
address: 127.0.0.1
user: ns_stats
group: ns_stats
port: 3000
pid: /home/ns_stats/www/ns_stats/shared/pids
rackup: /home/ns_stats/www/ns_stats/current/config.ru
log: /home/ns_stats/www/ns_stats/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
